# Generated by Django 4.1.6 on 2023-02-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_alter_meteoinfo_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteoinfo',
            name='date_time',
            field=models.DateTimeField(default='2023-02-08 05:09:40'),
        ),
    ]
