# Generated by Django 4.1.6 on 2023-02-13 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stations', '0012_alter_meteoinfo_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteoinfo',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meteoinfo',
            name='date_time',
            field=models.DateTimeField(default='2023-02-13 12:53:59'),
        ),
    ]
