# Generated by Django 4.1.6 on 2023-03-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0020_alter_meteoinfo_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meteoinfo',
            name='author',
        ),
        migrations.AlterField(
            model_name='meteoinfo',
            name='date_time',
            field=models.DateTimeField(default='2023-03-01 10:36:24'),
        ),
    ]
