# Generated by Django 4.1.6 on 2023-03-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0021_remove_meteoinfo_author_alter_meteoinfo_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteoinfo',
            name='date_time',
            field=models.DateTimeField(default='2023-03-01 10:46:24'),
        ),
    ]
